#!/usr/bin/env sh


#debug options
yabai -m config debug_output on

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 8)'); do
  yabai -m space --destroy 9
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

# define spaces
setup_space 1 im
setup_space 2 web
setup_space 3 calendar
setup_space 4 code
setup_space 5 terminal
setup_space 6 misc
setup_space 7 ssh
setup_space 8 meet

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
# yabai -m config window_opacity off
# yabai -m config window_border off

yabai -m config split_type auto
yabai -m config split_ratio 0.5
yabai -m config auto_balance off

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse support
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^Forcepoint NGFW VPN Client$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Time Machine$" manage=off sticky=on
yabai -m rule --add app="^Finder$" manage=off sticky=off
yabai -m rule --add app="^System Settings$" manage=off sticky=off
yabai -m rule --add app="^OBS Studio$" manage=off sticky=off
yabai -m rule --add app="^DeepL$" manage=off sticky=off

# Jetbrains specifics
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA|GoLand)$'
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
# yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on
yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on

# place apps to spaces
yabai -m rule --add app="^Messages$" space=^"im"
yabai -m rule --add app="^Element$" space=^"im"
yabai -m rule --add app="^Slack$" space=^"im"
yabai -m rule --add app="^Discord$" space=^"im"

yabai -m rule --add app="^Brave Browser$" space=^"web"
yabai -m rule --add app="^Microsoft Edge$" space=^"web"
yabai -m rule --add app="^Safari$" space="web"
yabai -m rule --add app="^Firefox$" space="web"

yabai -m rule --add app="^Chatbox$" space="calendar"
yabai -m rule --add app="^Calendar$" space="calendar"

yabai -m rule --add app="^GoLand$" space=^"code"
yabai -m rule --add app="^Code$" space=^"code"
yabai -m rule --add app="^Zed$" space=^"code"

yabai -m rule --add app="^Alacritty$" space=^"terminal"

yabai -m rule --add app="^Spotify$" space="misc"
yabai -m rule --add app="^Music$" space="misc"
yabai -m rule --add app="^Notes$" space=^"misc"

yabai -m rule --add app="^Royal TSX$" space=^"ssh"

yabai -m rule --add app="^Google Chrome$" title="^Google Meet.*$" space="meet"
yabai -m rule --add app="^zoom.us$" space=^"meet"
yabai -m rule --add app="^Microsoft Teams$" space="meet"


#iTerm specifics
#yabai -m rule --add app="^iTerm2$" space=^"terminal"
