[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/one-dark.toml"
]

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[window]
opacity = 0.95
dynamic_padding = false
blur = true
option_as_alt = "Both"
padding = { x = 5, y = 5 }
#[window.dimensions]
#columns = 500
#lines = 30

#[window.position]
#x = 0
#y = 0

[terminal]
shell = "/opt/homebrew/bin/zellij"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"
